apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  APP_DEBUG: {{ .Values.app.debug | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  LOG_CHANNEL: {{ .Values.app.logChannel | quote }}
  SESSION_DRIVER: {{ .Values.app.sessionDriver | quote }}
