name: Deploy to Production

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'app/**'
      - 'helm/**'

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  docker-push:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/callable-docker-push.yaml
    with:
      ENV_VARIABLES_PATH: ".github/variables/laravel.env"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  helm-deploy:
    needs: docker-push
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/callable-helm-deploy.yaml
    with:
      ENV_VARIABLES_PATH: ".github/variables/laravel.env"
      environment: production
    secrets:
      APP_KEY: ${{ secrets.APP_KEY }}
