name: Deploy to Production

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  helm-lint:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Deploy to prod')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: .github/variables/laravel.env

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: helm lint ./${{ env.HELM_TEMPLATE }}

  helm-deploy:
    needs: helm-lint
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Deploy to prod')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: .github/variables/laravel.env

      - name: Deploy
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE }} ./${{ env.HELM_TEMPLATE }} \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --set image.tag="${{ env.IMAGE_VERSION }}" \
            --set secret.appKey="${{ secrets.APP_KEY }}" \
            --set ingress.host="${{ env.INGRESS_HOST }}" \
            --kubeconfig ~/.kube/config-k8s-assignment \
            --atomic \
            --timeout 5m

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/laravel-app \
            -n ${{ env.NAMESPACE }} \
            --kubeconfig ~/.kube/config-k8s-assignment \
            --timeout=5m
