name: Deploy to Production

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'app/**'
      - 'helm/**'

jobs:
  docker-push:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/callable-docker-push.yaml
    with:
      image_tag: ${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  helm-deploy:
    needs: docker-push
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/callable-helm-deploy.yaml
    with:
      image_tag: ${{ github.sha }}
      environment: production
    secrets:
      APP_KEY: ${{ secrets.APP_KEY }}
